Update patch set 5
Patch Set 5:

> I have tested again with bento/ubuntu-16.04 vagrant box but still
 > get the error in line:
 > 
 > plugin.sh:start_monasca_services:213 :   start_service
 > monasca-thresh
 > 
 > Starting monasca-thresh fails with:
 > 
 > java.lang.RuntimeException: org.apache.storm.thrift.transport.TTransportException:
 > java.net.ConnectException: Connection refused (Connection refused)
 > Exception in thread "main" org.apache.storm.utils.NimbusLeaderNotFoundException:
 > Could not find leader nimbus from seed hosts [127.0.0.1]. Did you
 > specify a valid list of nimbus hosts for config nimbus.seeds?

It was worth checking out.
Ok, since this does not eliminate the need to have this workaround, are you fine with having this merged ?

Patch-set: 5
Label: Verified=0