Update patch set 12
Patch Set 12:

> (2 comments)
 > 
 > After deploying with 'vagrant up' I can see in /var/log/apache2/monasca-api.log:
 > 
 > IOError: [Errno 13] Permission denied: '/etc/monasca/api-config.ini'

That's interesting. I will double check, maybe sth was saved in environment prior to some changes while I was restacking instead of clean stack

Patch-set: 12