Update patch set 1
Patch Set 1:

It looks like the Zuul jobs have failed due to an unrelated failure: class HTTPUnprocessableEntity(falcon.OptionalRepresentation, falcon.HTTPError): AttributeError: module 'falcon' has no attribute 'OptionalRepresentation

Patch-set: 1
CC: Gerrit User 17669 <17669@4a232e18-c5a9-48ee-94c0-e04e7cca6543>