Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> It looks like the Zuul jobs have failed due to an unrelated failure: class HTTPUnprocessableEntity(falcon.OptionalRepresentation, falcon.HTTPError): AttributeError: module 'falcon' has no attribute 'OptionalRepresentation

It looks like this is a breaking changing in Falcon 3.0:

The class :class:`~.falcon.http_error.OptionalRepresentation` and the attribute :attr:`~.falcon.HTTPError.has_representation` were deprecated. The default error serializer now generates a representation for every error type that derives from :class:`falcon.HTTPError`. In addition, Falcon now ensures that any previously set response body is cleared before handling any raised exception. (#452)

https://github.com/falconry/falcon/blob/933851183ed9cce2d3411f890dca3e19385480f6/docs/changes/3.0.0.rst#breaking-changes

Patch-set: 1