Update patch set 3
Patch Set 3:

It looks like it is working better. The global "Grafana Home" button is displayed, although when I select it, it redirects to "about:blank"

However, if I create an alarm, and then select the "Graph" button on the alarm it redirects too I'm assuming the "proxy" at

http://192.168.10.6/dashboard/static/grafana/index.html#/dashboard/script/detail.js?name=cpu.idle_perc&threshold=[{"name": "cpu.idle_perc", "dimensions": {"hostname": "devstack", "service": "monitoring"}}]&api=http://192.168.10.6/dashboard/monitoring/proxy <http://192.168.10.6/dashboard/static/grafana/index.html#/dashboard/script/detail.js?name=cpu.idle_perc&threshold=%5B%7B%22name%22:%20%22cpu.idle_perc%22,%20%22dimensions%22:%20%7B%22hostname%22:%20%22devstack%22,%20%22service%22:%20%22monitoring%22%7D%7D%5D&api=http://192.168.10.6/dashboard/monitoring/proxy>

but that page says "Not Found"

When I try and add a data source, the "Test" button doesn't work and returns

Unknown error
Cannot read property 'message' of undefined

The stack trace in the "JS Error" panel is as follows:

TypeError: Cannot read property 'message' of undefined
at http://192.168.10.6:3000/public/app/core/services/backend_srv.js?bust=1459616781743:109:22
at processQueue (http://192.168.10.6:3000/public/vendor/angular/angular.js?bust=1459616781743:14567:28)
at http://192.168.10.6:3000/public/vendor/angular/angular.js?bust=1459616781743:14583:27
at Scope.$eval (http://192.168.10.6:3000/public/vendor/angular/angular.js?bust=1459616781743:15846:28)
at Scope.$digest (http://192.168.10.6:3000/public/vendor/angular/angular.js?bust=1459616781743:15657:31)
at Scope.$apply (http://192.168.10.6:3000/public/vendor/angular/angular.js?bust=1459616781743:15951:24)
at done (http://192.168.10.6:3000/public/vendor/angular/angular.js?bust=1459616781743:10364:47)
at completeRequest (http://192.168.10.6:3000/public/vendor/angular/angular.js?bust=1459616781743:10536:7)
at XMLHttpRequest.requestLoaded (http://192.168.10.6:3000/public/vendor/angular/angular.js?bust=1459616781743:10477:9)



I'm not quite sure how to set the datasource. I tried many combinations of the URL. What should that be

I've tried

192.168.10.6:8070/v2.0, the monasca api
292.168.10.6:5000/v2.0, the keystone api

and many combos.


It seems like the Keystone API is already known, since that is what I logged in with. The URL should be available in the Keystone catalog, unless you override it, but it seems to be required. 

I've enabled the proxy and Keystone Auth.

Patch-set: 3
Label: Verified=0