Update patch set 11
Patch Set 11:

I have tried to test with the newest ubuntu/xenial64 vagrant box and it requests credentials (default credentials are not set). For  bento/ubuntu-16.04 box I don't need the workaround with SCSI/SATA controller but monasca-thresh does not start with the error:

  java.lang.RuntimeException: org.apache.storm.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
  Caused by: org.apache.storm.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
  Caused by: java.net.ConnectException: Connection refused
  Exception in thread "main" org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts [127.0.0.1]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?

Patch-set: 11