Update patch set 12
Patch Set 12: -Code-Review -Workflow

Looks like the tests have broken since the last pass. We need to investigate at least this when running tox python unit tests:

sqlalchemy.exc.ArgumentError: Textual column expression 'metric_name' should be explicitly declared with text('metric_name'), or use column('metric_name') for more specificity

Patch-set: 12